name: enorsia
version: 1.0.9+9
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  input_quantity: ^1.2.3
  # Share package
  share_plus: ^7.1.0
  # flutter HTML
  flutter_html: ^3.0.0-beta.2
  # Responsiveness
#  sizer: ^2.0.15
  #Card Type
  credit_card_type_detector: ^3.0.0
  #sqflite
  sqflite: ^2.3.0
  # font
  google_fonts: ^5.1.0
  # Map
  google_maps_flutter: ^2.4.0
  geolocator: ^10.0.0
  #url launcher
  url_launcher: ^6.1.12
  # Images
  flutter_svg: ^2.0.7
  #carousel
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  #video player
  video_player: ^2.7.2
  # State Management
  get: 4.6.5
  # Network Call
  http: ^1.1.0
  # Local Storage
  get_storage: ^2.1.1
  # lotti
  lottie: ^2.6.0
  #simmer
  shimmer: ^3.0.0
  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.12.1
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/